version: '3.2'

services:

  auth-service:
    container_name: sabin2000/techrus-auth-service

    build:
      context: ./backend/src/services/authentication
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5400:5400"
      
    volumes:
       - /app/node_modules
       - ./backend/services/authentication:/app

  products-service:
    container_name: sabin2000/techrus-products-service

    build:
      context: ./backend/src/services/products
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5404:5404"

    volumes:
      - /app/node_modules
      - ./backend/services/products:/app

  categories-service:
    container_name: sabin2000/techrus-categories-service

    build:
      context: ./backend/src/services/categories
      dockerfile: Dockerfile
    
    restart: always

    ports:
      - "5401:5401"

    volumes:
      - /app/node_modules
      - ./backend/services/categories:/app

  coupon-service:
    container_name: sabin2000/techrus-coupons-service

    build:
      context: ./backend/src/services/coupons
      dockerfile: Dockerfile

    ports:
      - "5402:5402"

    volumes:
      - /app/node_modules
      - ./backend/src/services/coupons

  database-service:
    image: mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
volumes:
  mongodb_data_volume: