version: '3.2'

services:

  api-gateway-service:
    container_name: techrus-api-gateway-api
    image: sabin2000/techrus-api-gateway-service

    build:
      context: ../backend/services/api-gateway
      dockerfile: Dockerfile

    ports:
      - "5410:5410"

    volumes:
    - /app/node_modules
    - ../backend/services/api-gateway:/app

  shipping-service:
    container_name: techrus-shipping-service
    image: sabin2000/techrus-shipping-service

    build:
      context: ../backend/services/shipping-service
      dockerfile: Dockerfile

    ports:
      - "5411:5411"

    volumes:
      - /app/node_modules
      - ../backend/services/shipping-service:/app

  authentication-service:
    container_name: techrus-auth-api
    image: sabin2000/techrus-authentication-service

    networks:
      - my-service-network
      - auth-service

    build:
      context: ../backend/services/authentication-service
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5400:5400"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication-service:/app

  products-service:
    container_name: techrus-products-api
    image: sabin2000/techrus-products-service

    networks:
      - my-service-network

    build:
      context: ../backend/services/products-service
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5404:5404"

    volumes:
      - /app/node_modules
      - ../backend/services/products-service:/app

  coupons-service:
    container_name: techrus-coupons-api
    image: sabin2000/techrus-coupons-service

    build:
      context: ../backend/services/coupons-service
      dockerfile: Dockerfile

    ports:
      - "5402:5402"

    volumes:
      - /app/node_modules
      - ../backend/services/coupons-service:/app

  orders-service:
    container_name: techrus-orders-api
    image: sabin2000/techrus-orders-service


    build:
      context: ../backend/services/orders-service
      dockerfile: Dockerfile

    ports:
      - "5403:5403"

    volumes:
      - /app/node_modules
      - ../backend/services/orders-service:/app

  reviews-service:
      container_name: techrus-reviews-api

      build:
        context: ../backend/services/reviews-service
        dockerfile: Dockerfile

      ports:
       - "5407:5407"

      volumes:
       - /app/node_modules
       - ../backend/services/reviews-service:/app

  payments-service:
    container_name: techrus-payments-api
    image: sabin2000/techrus-payments-service
    build:
      context: ../backend/services/payments-service
      dockerfile: Dockerfile

    ports:
      - "5406:5406"

    volumes:
      - /app/node_modules
      - ../backend/services/payments-service:/app

  eventbus-service:
    container_name: eventbus-api

    build:
      context: ../backend/services/event-bus-service
      dockerfile: Dockerfile

    ports:
      - "6500:6500"

    volumes:
      - /app/node_modules
      - ../backend/services/event-bus-service:/app
    
  frontend-service:
    container_name: techrus-frontend-service

    build:  
      context: ../frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - ../frontend:/app
        
volumes:
  mongodb_data_volume: