version: '3.2'

services:

  api-gateway-service:
    container_name: techrus-api-gateway-api
    image: sabin2000/techrus-api-gateway-service

    build:
      context: ../backend/services/api-gateway
      dockerfile: Dockerfile

    ports:
      - "6000:6000"

    volumes:
    - /app/node_modules
    - ../backend/services/api-gateway:/app

  auth-service:
    container_name: techrus-auth-api
    image: sabin2000/techrus-auth-service

    build:
      context: ../backend/services/authentication
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5400:5400"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication:/app

  customers-service:
    container_name: techrus-customers-api
    image: sabin2000/techrus-customers-service

    build:
      context: ../backend/services/customers
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5420:5420"
      
    volumes:
       - /app/node_modules
       - ../backend/services/customers:/app

  products-service:
    container_name: techrus-products-api
    image: sabin2000/techrus-products-service

    build:
      context: ../backend/services/products
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5404:5404"

    volumes:
      - /app/node_modules
      - ../backend/services/products:/app

  categories-service:
    container_name: techrus-categories-api
    image: sabin2000/techrus-categories-service

    build:
      context: ../backend/services/categories
      dockerfile: Dockerfile
    
    restart: always

    ports:
      - "5401:5401"

    volumes:
      - /app/node_modules
      - ../backend/services/categories:/app

  coupon-service:
    container_name: techrus-coupons-api
    image: sabin2000/techrus-coupons-service

    build:
      context: ../backend/services/coupons
      dockerfile: Dockerfile

    ports:
      - "5402:5402"

    volumes:
      - /app/node_modules
      - ../backend/services/coupons:/app

  orders-service:
    container_name: techrus-orders-api
    image: sabin2000/techrus-orders-service

    build:
      context: ../backend/services/orders
      dockerfile: Dockerfile

    ports:
      - "5403:5403"

    volumes:
      - /app/node_modules
      - ../backend/services/orders:/app

  reviews-service:
      container_name: techrus-reviews-api

      build:
        context: ../backend/services/reviews
        dockerfile: Dockerfile

      ports:
       - "5407:5407"

      volumes:
       - /app/node_modules
       - ../backend/services/reviews:/app

  frontend-service:
    container_name: techrus-frontend-service

    build:  
      context: ../frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - ../frontend:/app

  database-service:
    image: mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
volumes:
  mongodb_data_volume:

networks:
  my-service-network:
    driver: bridge