version: '3.2'

services:

  auth-service:
    container_name: sabin2000/techrus-auth-service

    build:
      context: ./backend/src/services/authentication
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5400:5400"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication:/app