export const REGISTER_CUSTOMER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_CUSTOMER_FAIL = "REGISTER_USER_FAIL"

export const VERIFY_CUSTOMER_EMAIL_REQUEST = "VERIFY_CUSTOMER_EMAIL_REQUEST";
export const VERIFY_CUSTOMER_EMAIL_SUCCESS = "VERIFY_CUSTOMER_EMAIL_SUCCESS";
export const VERIFY_CUSTOMER_EMAIL_FAIL = "VERIFY_CUSTOMER_EMAIL_FAIL";

export const LOGIN_CUSTOMER_REQUEST = "LOGIN_CUSTOMER_REQUEST";
export const LOGIN_CUSTOMER_SUCCESS = "LOGIN_CUSTOMER_SUCCESS";
export const LOGIN_CUSTOMER_FAIL = "LOGIN_CUSTOMER_FAIL"

export const VERIFY_LOGIN_MFA_REQUEST = "VERIFY_LOGIN_MFA_REQUEST";
export const VERIFY_LOGIN_MFA_SUCCESS = "VERIFY_LOGIN_MFA_SUCCESS";
export const VERIFY_LOGIN_MFA_FAIL = "VERIFY_LOGIN_MFA_FAIL";

export const LOAD_CUSTOMER_REQUEST = "LOAD_CUSTOMER_REQUEST";
export const LOAD_CUSTOMER_SUCCESS = "LOAD_CUSTOMER_SUCCESS";
export const LOAD_CUSTOMER_FAIL = "LOAD_CUSTOMER_FAIL"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UDPATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"