export const FETCH_ALL_COUPONS_REQUEST = "FETCH_ALL_COUPONS_REQUEST";
export const FETCH_ALL_COUPONS_SUCCESS = "FETCH_ALL_COUPONS_SUCCESS";
export const FETCH_ALL_COUPONS_FAIL = "FETCH_ALL_COUPONS_FAIL";

export const FETCH_SINGLE_COUPON_REQUEST = "FETCH_SINGLE_COUPON_BY_ID";
export const FETCH_SINGLE_COUPON_BY_SUCCESS = "FETCH_ALL_COUPONS_REQUEST";
export const FETCH_SINGLE_COUPON_BY_FAIL = "FETCH_ALL_COUPONS_REQUEST";

export const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST"
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL";

export const EDIT_COUPON_DETAILS_REQUEST = "EDIT_COUPON_DETAILS_REQUEST"
export const EDIT_COUPON_DETAILS_SUCCESS = "EDIT_COUPON_DETAILS_SUCCESS";
export const EDIT_COUPON_DETAILS_FAIL = "EDIT_COUPON_DETAILS_SUCCESS";

export const EDIT_COUPON_EXPIRATION_REQUEST = "EDIT_COUPON_DETAILS_SUCCESS";
export const EDIT_COUPON_EXPIRATION_SUCCESS = "EDIT_COUPON_DETAILS_SUCCESS";
export const EDIT_COUPON_EXPIRATION_FAIL = "EDIT_COUPON_DETAILS_SUCCESS";

export const DELETE_COUPONS_REQUEST = "DELETE_COUPONS_REQUEST"
export const DELETE_COUPONS_SUCCESS = "DELETE_COUPONS_SUCCESS";
export const DELETE_COUPONS_FAIL = "DELETE_COUPONS_FAIL"

export const DELETE_SINGLE_COUPON_REQUEST = "DELETE_COUPON_BY_ID_REQUEST"
export const DELETE_SINGLE_COUPON_SUCCESS = "DELETE_COUPON_BY_ID_REQUEST"
export const DELETE_SINGLE_COUPON_FAIL = "DELETE_COUPON_BY_ID_REQUEST"