export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST"
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL"

export const CREATE_ORDER_REQUEST = "FETCH_ORDERS_SUCCESS"
export const CREATE_ORDER_SUCCESS = "FETCH_ORDERS_SUCCESS"
export const CREATE_ORDER_FAIL = "FETCH_ORDERS_SUCCESS"

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST"
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS"
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL"