export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST"
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS"
export const FETCH_ALL_PRODUCTS_FAIL = "FETCH_ALL_PRODUCTS_FAIL"

export const FETCH_SINGLE_PRODUCT_REQUEST = "FETCH_SINGLE_PRODUCT_REQUEST"
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS"
export const FETCH_SINGLE_PRODUCT_FAIL = "FETCH_SINGLE_PRODUCT_FAIL"

export const FETCH_NEW_PRODUCTS_REQUEST = "FETCH_SINGLE_PRODUCT_REQUEST"
export const FETCH_NEW_PRODUCTS_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS"
export const FETCH_NEW_PRODUCTS_FAIL = "FETCH_SINGLE_PRODUCT_FAIL"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCTS_REQUEST"
export const CREATE_PRODUCT_FAIL = "FETCH_ALL_PRODUCTS_REQUEST"

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL"

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST"
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS"
export const DELETE_PRODUCTS_FAIL = "DELETE_PRODUCTS_FAIL"

export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAIL = "FILE_UPLOAD_FAILT";

export const CLEAR_ERRORS = "CLEAR_ERRORS"