export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST"
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_REQUEST"
export const FETCH_ALL_PRODUCTS_FAIL = "FETCH_ALL_PRODUCTS_REQUEST"

export const FETCH_SINGLE_PRODUCT_REQUEST = "FETCH_SINGLE_PRODUCT_REQUEST"
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS"
export const FETCH_SINGLE_PRODUCT_FAIL = "FETCH_SINGLE_PRODUCT_FAIL"

export const FETCH_NEW_PRODUCTS_REQUEST = "FETCH_SINGLE_PRODUCT_REQUEST"
export const FETCH_NEW_PRODUCTS_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS"
export const FETCH_NEW_PRODUCTS_FAIL = "FETCH_SINGLE_PRODUCT_FAIL"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCTS_REQUEST"
export const CREATE_PRODUCT_FAIL = "FETCH_ALL_PRODUCTS_REQUEST"

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL"