export const SAVE_SHIPPING_INFO_REQUEST = "SAVE_SHIPPING_INFO_REQUEST"
export const SAVE_SHIPPING_INFO_SUCCESS = "SAVE_SHIPPING_INFO_SUCCESS"
export const SAVE_SHIPPING_INFO_FAIL = "SAVE_SHIPPING_INFO_FAIL"

export const EDIT_SHIPPING_INFO_REQUEST = "EDIT_SHIPPING_INFO_REQUEST"
export const EDIT_SHIPPING_INFO_SUCCESS = "EDIT_SHIPPING_INFO_SUCCESS"
export const EDIT_SHIPPING_INFO_FAIL = "EDIT_SHIPPING_INFO_FAIL"

export const EDTI_SHIPPING_STATUS_REQUEST = "EDIT_SHIPPING_STATUS_REQUEST"
export const EDIT_SHIPPING_STATUS_SUCCESS = "EDIT_SHIPPING_STATUS_SUCCESS"
export const EDIT_SHIPPING_STATUS_FAIL = "EDIT_SHIPPING_STATUS_FAIL"

export const FETCH_SHIPPING_INFO_REQUEST = "FETCH_SHIPPING_INFO_REQUEST"
export const FETCH_SHIPPING_INFO_SUCCESS = "FETCH_SHIPPING_INFO_SUCCESS"
export const FETCH_SHIPPING_INFO_FAIL = "FETCH_SHIPPING_INFO_FAIL"

export const DELETE_SHIPPING_DETAILS_REQUEST = "FETCH_SHIPPING_INFO_REQUEST"
export const DELETE_SHIPPING_DETAILS_SUCCESS = "FETCH_SHIPPING_INFO_SUCCESS"
export const DELETE_SHIPPING_DETAILS_FAIL = "DELETE_SHIPPING_DETAILS_FAIL"