export const SAVE_SHIPPING_INFO_REQUEST = "SAVE_SHIPPING_INFO_REQUEST"
export const SAVE_SHIPPING_INFO_SUCCESS = "SAVE_SHIPPING_INFO_SUCCESS"
export const SAVE_SHIPPING_INFO_FAIL = "SAVE_SHIPPING_INFO_FAIL"

export const EDIT_SHIPPING_INFO_SUCCESS = ""