export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_SINGLE_USER_REQUEST = "FETCH_SINGLE_USER_REQUEST"
export const FETCH_SINGLE_USER_SUCCESS = "FETCH_SINGLE_USER_SUCCESS"
export const FETCH_SINGLE_USER_FAIL = "FETCH_SINGLE_USER_FAIL"

export const EDIT_USER_DETAILS_REQUEST = "FETCH_SINGLE_USER_REQUEST"
export const EDIT_USER_DETAILS_SUCCESS = "FETCH_SINGLE_USER_REQUEST"
export const EDIT_USER_DETAILS_FAIL = "FETCH_SINGLE_USER_REQUEST"

export const EDIT_USER_SHIFTS_REQUEST = "EDIT_USER_SHIFTS_REQUEST"
export const EDIT_USER_SHIFTS_SUCCESS = "EDIT_USER_SHIFTS_SUCCESS"
export const EDIT_USER_SHIFTS_FAIL = "EDIT_USER_SHIFTS_FAIL"

export const DELETE_USERS_REQUEST = "DELETE_USERS_REQUEST"
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS"
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL"

export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS"