export const AUTH_URI_REGISTER = 'https://techrus.dev/api/v1/auth/register'
export const AUTH_URI_VERIFY_EMAIL = 'https://techrus.dev/api/v1/auth/verify-email'
export const AUTH_URI_LOGIN = 'https://techrus.dev/api/v1/auth/login'
export const AUTH_URI_VERIFY_LOGIN = 'https://techrus.dev/api/v1/auth/verify-login'
export const AUTH_URI_LOGOUT = 'https://techrus.dev/api/v1/auth/logout'