apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway-service

  labels:
    name: api-gateway-service

spec:
  replicas: 1
  
  selector: 
    matchLabels:
      app: api-gateway-service

  template:
    metadata:
    
      labels:
        app: api-gateway-service

    spec: 
     containers:

       - name: api-gateway-service
         image: sabin2000/techrus-api-gateway-service

         ports:
           - containerPort: 6000